server: 
  port: 8084
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/trafficlight?serverTimezone=GMT%2B8&useSSL=false
    username: root #用户名
    password: root
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
  - classpath:mybatis/mapper/*.xml